/*
Nivea Gigen
S5C
CHN18CS092
ROLL NO.: 43
--------------------------------------------------------------------------------
      TASK11
-------------------------------------------------------------------------------
Write a database trigger that prevent changes to emp table from 
5pm to 12am(statement level trigger)
---------------------------------------------------------------------------------
     CODE
----------------------------------------------------------------------------------
 */
CREATE TABLE EMPLOYEE (CODE CHAR(10),NAME CHAR(50),DOB DATE NOT NULL,DESIGNATION CHAR(30),SALARY INT);
INSERT INTO EMPLOYEE VALUES ('A','MONIKA','1973-08-20','PRINCIPAL','100000');
INSERT INTO EMPLOYEE VALUES ('B','ELIZABETH','1980-09-25','TEACHER','40000');
INSERT INTO EMPLOYEE VALUES ('C','JENNIFER','1975-04-30','HOD','60000');
INSERT INTO EMPLOYEE VALUES ('D','ROSANNA','1985-06-05','CLERK','25000');
INSERT INTO EMPLOYEE VALUES ('E','PHILOMINA','1982-09-26','ACCOUNTANT','30000');
INSERT INTO EMPLOYEE VALUES ('F','LUCY','1986-08-08','SYSTEM ANALYST','28000');
DELIMITER $$
CREATE TRIGGER INSERT_PREVENT
BEFORE INSERT
ON EMPLOYEE FOR EACH ROW
BEGIN
IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
END IF;
END $$
DELIMITER ;
DELIMITER $$
CREATE TRIGGER UPDATE_PREVENT
BEFORE UPDATE
ON EMPLOYEE FOR EACH ROW
BEGIN
IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
END IF;
END $$
DELIMITER ;
DELIMITER $$
CREATE TRIGGER DELETE_PREVENT
BEFORE DELETE
ON EMPLOYEE FOR EACH ROW
BEGIN
IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
END IF;
END $$
DELIMITER ;
